[features]
seeds = false
skip-lint = false
[programs.localnet]
ai_nft_generator = "ATDso9o279ksvov6rAm4MoXQrxFPQX1q5qiX4yXQLnxh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/hackerboy/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
